### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MinecraftDoodler** [lukas2005/Device-Mod-Apps#2]
Launched in IntelliJ IDEA environment,
device_api: 0.1.0
Computer: Macintosh
[crash-2017-10-20_18.13.36-client.txt](https://github.com/lukas2005/Device-Mod-Apps/files/1403499/crash-2017-10-20_18.13.36-client.txt)

**Comment by lukas2005** [comment]
fixed by updating the jar in release
