### ISSUE TITLE
Code doesnt complie

### ISSUE THREAD

**Issue by Aregev2** [lukas2005/Device-Mod-Apps#6]
The jxBrowser in your project does not work, 
CreateProcess error=206, The filename or extension is too long
This is the exception

Aregev2

**Comment by lukas2005** [comment]
what os?
and please post full log
and wdym by "doesnt compile" ? 
like the game doesnt run? or gradle task fails?
also dev env or normal?

**Comment by lukas2005** [comment]
PS. if u want to build from sources use `gradlew buildAll`

**Comment by lukas2005** [comment]
More info needed: Closing
