### ISSUE TITLE
Cannot run on Windows

### ISSUE THREAD

**Issue by JMK19** [lukas2005/Device-Mod-Apps#8]
It seems on my system on Windows 10 that the game will not launch with this mod installed (I do have the Device Mod installed).

I got some sort of a severe mod loading error while loading this mod.

Also, i noticed that there are only 2 versions of the mod, linux32 and mac. I am running Windows, so could that be the problem?

**Comment by lukas2005** [comment]
Check out releases i uploaded a windows version here (gonna submit t to curse soon i just have to fix one thing)

**Comment by lukas2005** [comment]
https://github.com/lukas2005/Device-Mod-Apps/releases

**Comment by JMK19** [comment]
I am still getting an error:
`The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from lukas2005's Device Mod Apps (lda)`

**Comment by lukas2005** [comment]
full log please

**Comment by JMK19** [comment]
Here's the part of the log with the error:
https://pastebin.com/RJW4qx97

**Comment by JMK19** [comment]
I figured out the problem!
It seems that any mod that does not support the version of the Device Mod i have will "Catch an exception"  while MC loads.
I just updated to the Iconic update and now another device mod addon doesn't work. The reason your's didnt is because i was running pre6, maybe your mod is not updated for it?
I'm waiting for the other addons to just update to the new versions.
